//! Small, explicit desktop transport boundary; not a serialization of domain internals.
use dnagent_domain::{Strand, Topology};
use serde::Serialize;
use std::path::Path;
use ts_rs::TS;

#[derive(Debug, Serialize, TS)]
pub struct Segment {
    pub start: u32,
    pub length: u32,
}

#[derive(Debug, Serialize, TS)]
pub struct Feature {
    pub id: String,
    pub label: String,
    pub kind: String,
    pub color: Option<String>,
    pub strand: Direction,
    /// Ordered source parts. Circular parts may cross the origin.
    pub parts: Vec<Segment>,
}

#[derive(Debug, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum Direction {
    Forward,
    Reverse,
    Unknown,
}

#[derive(Debug, Serialize, TS)]
pub struct Diagnostic {
    pub code: String,
    pub message: String,
}

#[derive(Debug, Serialize, TS)]
pub struct UnplacedPrimer {
    pub name: String,
    pub sequence_5to3: String,
    pub description: Option<String>,
}

#[derive(Debug, Serialize, TS)]
pub struct Document {
    pub name: String,
    pub sequence: String,
    /// Complement aligned to forward coordinates, left-to-right 3′→5′.
    pub aligned_complement_3to5: String,
    /// Imported oligos only; binding coordinates are not retained by the importer.
    pub unplaced_primers: Vec<UnplacedPrimer>,
    pub circular: bool,
    pub features: Vec<Feature>,
    pub warnings: Vec<Diagnostic>,
}

/// Prototype limit bounds frontend rendering; not a biological restriction.
const MAX_BASES: usize = 100_000;

pub fn open_document(path: &Path) -> Result<Document, Diagnostic> {
    let report = dnagent_app::open_path(path).map_err(|error| Diagnostic {
        code: "import_failed".into(),
        message: error.to_string(),
    })?;
    let record = report.record;
    if record.sequence().len() > MAX_BASES {
        return Err(Diagnostic {
            code: "prototype_size_limit".into(),
            message: "The prototype viewer supports at most 100,000 bases".into(),
        });
    }
    let features = record
        .features()
        .iter()
        .map(|feature| Feature {
            id: feature.id().as_str().into(),
            label: feature.label().into(),
            kind: feature.kind().into(),
            color: feature.display().color.clone(),
            strand: match feature.location().strand() {
                Strand::Forward => Direction::Forward,
                Strand::Reverse => Direction::Reverse,
                Strand::Unknown => Direction::Unknown,
            },
            parts: feature
                .location()
                .parts()
                .iter()
                .map(|part| Segment {
                    start: u32::try_from(part.start().get()).expect("bounded record"),
                    length: u32::try_from(part.length().get()).expect("bounded record"),
                })
                .collect(),
        })
        .collect();
    Ok(Document {
        name: record.name().into(),
        sequence: record.sequence().as_str().into(),
        aligned_complement_3to5: record.sequence().aligned_complement_3to5(),
        unplaced_primers: dnagent_app::primer_views(&record)
            .iter()
            .map(|primer| UnplacedPrimer {
                name: primer.name.clone(),
                sequence_5to3: primer.sequence.as_str().into(),
                description: primer.description.clone(),
            })
            .collect(),
        circular: record.topology() == Topology::Circular,
        features,
        warnings: report
            .warnings
            .into_iter()
            .map(|warning| Diagnostic {
                code: warning.code,
                message: warning.message,
            })
            .collect(),
    })
}

/// Generated from Rust DTOs; the frontend must not maintain parallel definitions.
#[must_use]
pub fn typescript() -> String {
    let declarations = [
        Segment::decl(),
        Direction::decl(),
        Feature::decl(),
        Diagnostic::decl(),
        UnplacedPrimer::decl(),
        Document::decl(),
    ];
    let mut result = String::from(
        "// Generated by cargo run -p dnagent-desktop-api --example export_types. Do not edit.\n",
    );
    for declaration in declarations {
        result.push_str("export ");
        for line in declaration.lines() {
            result.push_str(line.trim_end());
            result.push('\n');
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generated_contract_is_current() {
        assert_eq!(
            typescript(),
            include_str!("../../../desktop/src/bindings.ts")
        );
    }
    #[test]
    fn imports_multipart_and_returns_structured_failure() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/formats/snapgene");
        let doc = open_document(&root.join("synthetic_linear.dna")).unwrap();
        assert!(!doc.circular);
        assert_eq!(doc.unplaced_primers.len(), 1);
        assert_eq!(doc.unplaced_primers[0].name, "synthetic primer");
        assert_eq!(doc.unplaced_primers[0].sequence_5to3, "ACGTN");
        assert_eq!(
            doc.unplaced_primers[0].description.as_deref(),
            Some("retained description")
        );
        assert_eq!(doc.aligned_complement_3to5.len(), doc.sequence.len());
        assert_eq!(
            doc.aligned_complement_3to5,
            dnagent_domain::DnaSeq::new(&doc.sequence)
                .unwrap()
                .aligned_complement_3to5()
        );
        assert!(
            doc.features
                .iter()
                .any(|f| f.parts.len() > 1 && matches!(f.strand, Direction::Reverse))
        );
        assert_eq!(
            open_document(&root.join("missing.dna")).unwrap_err().code,
            "import_failed"
        );
    }
}
