[package]
name = "dnagent-desktop-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dnagent-app = { path = "../dnagent-app" }
dnagent-library = { path = "../dnagent-library" }
dnagent-domain = { path = "../dnagent-domain" }
serde.workspace = true
serde_json.workspace = true
dnagent-formats = { path = "../dnagent-formats" }
ts-rs = "11"


[lints]
workspace = true
