[package]
name = "dnagent-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dnagent-domain = { path = "../dnagent-domain" }
dnagent-formats = { path = "../dnagent-formats" }
dnagent-format-snapgene = { path = "../dnagent-format-snapgene" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
