[package]
name = "dnagent-desktop"
version = "0.2.0"
edition = "2024"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri-plugin-dialog = "2"
tauri = { version = "2", features = [] }
dnagent-desktop-api = { path = "../../crates/dnagent-desktop-api" }
dnagent-app = { path = "../../crates/dnagent-app" }
dnagent-agent-mcp = { path = "../../crates/dnagent-agent-mcp" }

[workspace]
