// Generated by cargo run -p dnagent-desktop-api --example export_types. Do not edit.
export type Segment = { start: number, length: number, };
export type Direction = "forward" | "reverse" | "unknown";
export type Feature = { id: string, label: string, kind: string, color: string | null, strand: Direction,
/**
 * Ordered source parts. Circular parts may cross the origin.
 */
parts: Array<Segment>, };
export type Diagnostic = { code: string, message: string, };
export type Document = { name: string, sequence: string, circular: boolean, features: Array<Feature>, warnings: Array<Diagnostic>, };
