// Generated by cargo run -p dnagent-desktop-api --example export_types. Do not edit.
export type Segment = { start: number, length: number, };
export type Direction = "forward" | "reverse" | "unknown";
export type Feature = { id: string, label: string, kind: string, color: string | null, strand: Direction,
/**
 * Ordered source parts. Circular parts may cross the origin.
 */
parts: Array<Segment>, };
export type Diagnostic = { code: string, message: string, };
export type UnplacedPrimer = { name: string, sequence_5to3: string, description: string | null, };
export type FeatureTranslation = { feature_id: string, table: number,
/**
 * One letter per codon; stops are `*`.
 */
protein: string,
/**
 * Reference positions of each codon's three coding bases, flattened (3 per codon).
 */
codon_positions: Array<number>, initiator_as_methionine: boolean,
/**
 * Comparison with the imported `translation` qualifier; null when absent.
 */
imported_matches: boolean | null, warnings: Array<Diagnostic>, };
export type FrameTranslation = { strand: Direction, offset: number, first: number, protein: string, };
export type Orf = { id: string, strand: Direction, start: number, length: number,
/**
 * Amino acids excluding the stop.
 */
codons: number, protein: string, };
export type Document = { name: string, sequence: string,
/**
 * Complement aligned to forward coordinates, left-to-right 3′→5′.
 */
aligned_complement_3to5: string,
/**
 * Imported oligos only; binding coordinates are not retained by the importer.
 */
unplaced_primers: Array<UnplacedPrimer>, circular: boolean, features: Array<Feature>, warnings: Array<Diagnostic>,
/**
 * CDS translations in source order; untranslatable CDSs are listed in `translation_skipped`.
 */
translations: Array<FeatureTranslation>, translation_skipped: Array<Diagnostic>,
/**
 * Frames +1, +2, +3, -1, -2, -3.
 */
frames: Array<FrameTranslation>,
/**
 * ORFs of at least `orf_min_codons`; the GUI may filter to longer ones.
 */
orfs: Array<Orf>, orf_min_codons: number, };
export type EditState = { document_id: number,
/**
 * Position in the edit history (0 = as opened).
 */
revision: number, can_undo: boolean, can_redo: boolean,
/**
 * Changes since opening or the last save.
 */
dirty: boolean,
/**
 * Features added in this session (the only ones that can be deleted).
 */
added_feature_ids: Array<string>, source_path: string,
/**
 * Last GenBank save of this session, if any.
 */
saved_path: string | null, };
export type DocumentState = { document: Document, edit: EditState, };
export type TranslateRequest = { table: number, codon_start: number, };
export type FeatureRequest = { start: number, end: number, strand: Direction, kind: string, label: string, color: string | null, translate: TranslateRequest | null,
/**
 * Optional `/note` qualifier.
 */
note?: string, };
export type FeaturePreview = { length: number, parts: Array<Segment>,
/**
 * One letter per codon (stops as `*`), when translated.
 */
protein: string | null, warnings: Array<Diagnostic>, };
export type SaveResult = { state: DocumentState, warnings: Array<Diagnostic>, };
export type RangeRequest = { start: number, end: number, };
export type HandoffItem = { document_id: number, active: boolean, selection: RangeRequest | null, selected_feature_id: string | null, };
export type HandoffResult = { workspace: string, context_path: string, snapshots: Array<string>, prompt: string, };
export type FileStamp = { path: string, modified_ms: number, size: number, };
export type Proposal = {
/**
 * Stable within one detection: `<library id>@<start><strand letter>`.
 */
key: string, library_id: number, name: string, kind: string, color: string | null, strand: Direction, start: number, length: number,
/**
 * Existing features with exactly this span and a compatible strand.
 */
annotated_as: Array<string>,
/**
 * The first longer proposal whose span contains this one (e.g. "lac" in "lac promoter").
 */
contained_in: string | null,
/**
 * NCBI table and codon start from the library entry, for CDS proposals.
 */
translate: [number, number] | null, };
export type DetectionResult = {
/**
 * False when there is no library yet (see `message`).
 */
available: boolean, message: string, library_features: number, min_length: number, proposals: Array<Proposal>, };
export type EnzymeInfo = { name: string,
/**
 * IUPAC recognition sequence (may be degenerate or interrupted).
 */
site: string, top_cut_offset: number, bottom_cut_offset: number,
/**
 * `blunt`, `five_prime` or `three_prime`.
 */
overhang: string, overhang_length: number, };
export type EnzymeCatalogueInfo = { source: string, version: string, enzymes: Array<EnzymeInfo>,
/**
 * Enzymes the source lists but DNAgent cannot model yet (e.g. two-sided cutters).
 */
unsupported: number, };
export type EnzymeCount = { name: string, sites: number, cuts: number, };
export type Site = { enzyme: string,
/**
 * Recognition start and length (may wrap on circular molecules).
 */
start: number, length: number, strand: Direction,
/**
 * Top/bottom strand cut boundaries; null when outside a linear molecule.
 */
top_cut: number | null, bottom_cut: number | null, cleavage_available: boolean, };
export type FragmentEndInfo = { enzymes: Array<string>,
/**
 * `blunt`, `five_prime` or `three_prime`.
 */
overhang: string, overhang_sequence: string,
/**
 * The molecule's original end (linear input), not a cut.
 */
original_terminus: boolean, };
export type Fragment = { id: string,
/**
 * Top-strand start and length (may wrap on circular molecules).
 */
start: number, length: number, left: FragmentEndInfo | null, right: FragmentEndInfo | null, };
