"""Generate crates/dnagent-domain/src/genetic_codes.rs from the pinned NCBI gc.prt.

Source: https://ftp.ncbi.nlm.nih.gov/entrez/misc/data/gc.prt (version 4.6),
retrieved 2026-09-28 and committed as references/ncbi/gc.prt. NCBI data are in the
public domain. Run: python3 scripts/generate_genetic_codes.py
"""

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "references/ncbi/gc.prt"
TARGET = ROOT / "crates/dnagent-domain/src/genetic_codes.rs"
EXPECTED_SHA256 = "2aecbdd09ecc5e0d233c105090a593737298ef93d88f6bc0c1bef26df6051a04"


def main() -> None:
    raw = SOURCE.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    assert digest == EXPECTED_SHA256, f"gc.prt changed: {digest}"
    text = "\n".join(line for line in raw.decode("ascii").splitlines() if not line.lstrip().startswith("--"))
    tables = []
    for block in re.findall(r"\{(.*?)\}", text, re.S):
        names = re.findall(r'name\s+"([^"]*)"', block)
        ident = re.search(r"\bid\s+(\d+)", block)
        aa = re.search(r'ncbieaa\s+"([^"]{64})"', block)
        starts = re.search(r'sncbieaa\s+"([^"]{64})"', block)
        if not (names and ident and aa and starts):
            continue
        tables.append((int(ident.group(1)), " ".join(names[0].split()), aa.group(1), starts.group(1)))
    assert len(tables) == 27, len(tables)
    lines = [
        "// @generated by scripts/generate_genetic_codes.py from references/ncbi/gc.prt",
        f"// (NCBI genetic codes version 4.6, SHA-256 {digest}). Do not edit.",
        "//! NCBI translation tables. Codon index = 16·b1 + 4·b2 + b3 with T=0, C=1, A=2, G=3.",
        "",
        "/// One NCBI translation table: amino acids (`*` = stop) and start markers (`M`).",
        "#[derive(Debug)]",
        "pub struct GeneticCodeData {",
        "    pub id: u8,",
        "    pub name: &'static str,",
        "    pub amino_acids: &'static [u8; 64],",
        "    pub starts: &'static [u8; 64],",
        "}",
        "",
        "pub const GC_PRT_VERSION: &str = \"4.6\";",
        f"pub const GC_PRT_SHA256: &str = \"{digest}\";",
        "",
        "pub static TABLES: &[GeneticCodeData] = &[",
    ]
    for ident, name, aa, starts in sorted(tables):
        lines += [
            "    GeneticCodeData {",
            f"        id: {ident},",
            f"        name: {name!r},".replace("'", '"'),
            f'        amino_acids: b"{aa}",',
            f'        starts: b"{starts}",',
            "    },",
        ]
    lines.append("];")
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(tables)} tables to {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
