// Ground truth: the validated dnagent CLI, run at test time and cached per process.
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

export const REPO_ROOT = resolve(import.meta.dirname, '../../..');
export const BINARY = process.env.DNAGENT_BINARY ?? resolve(REPO_ROOT, 'target/debug/dnagent');
export const CLI_COMMANDS = ['inspect', 'features', 'primers', 'translate', 'orfs', 'sites', 'digest', 'enzymes', 'detect-features', 'isoforms'] as const;
/** Built by global-setup from the public fixtures; the e2e server reads the same file. */
export const FEATURE_LIBRARY = resolve(REPO_ROOT, 'desktop/e2e/artifacts/feature-library.sqlite');
/** Generated by global-setup (repository-relative, so scenarios can open it as `file`). */
export const LARGE_LOCUS = 'desktop/e2e/artifacts/synthetic_large.locus.json';
/** Environment for every dnagent run: built-in enzymes and the test feature library. */
export const CLI_ENV = { ...process.env, DNAGENT_ENZYMES: 'builtin', DNAGENT_FEATURE_DB: FEATURE_LIBRARY };
/** Commands that take no input file. */
const NO_INPUT: readonly CliCommand[] = ['enzymes'];
export type CliCommand = (typeof CLI_COMMANDS)[number];

const cache = new Map<string, unknown>();

export function assertBinary(): void {
  if (!existsSync(BINARY)) {
    throw new Error(`dnagent binary not found at ${BINARY}. Run \`cargo build -p dnagent-cli --locked\` from the repository root, or set DNAGENT_BINARY.`);
  }
}

/** The JSON envelope of `dnagent <command> <fixture> --output json` (failure envelopes included). */
export function cli(command: CliCommand, fixture: string, args: string[] = []): Record<string, unknown> {
  const key = [command, fixture, ...args].join(' ');
  // Only committed fixtures are immutable; saved files and workspace files change during a scenario.
  if (!fixture.startsWith('fixtures/')) cache.delete(key);
  if (!cache.has(key)) {
    assertBinary();
    let stdout: string;
    try {
      const input = NO_INPUT.includes(command) ? [] : [fixture];
      // The built-in enzyme set, like the e2e server: a locally installed REBASE must not change results.
      stdout = execFileSync(BINARY, [command, ...input, ...args, '--output', 'json'], { cwd: REPO_ROOT, encoding: 'utf8', env: CLI_ENV });
    } catch (error) {
      // Runtime failures still print a JSON envelope on stdout with a nonzero exit.
      stdout = String((error as { stdout?: string }).stdout ?? '');
      if (!stdout.trim()) throw new Error(`dnagent ${key} failed without JSON output: ${String(error)}`);
    }
    cache.set(key, JSON.parse(stdout));
  }
  return cache.get(key) as Record<string, unknown>;
}
